/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProductosTienda;

import MenuPrincipal.InicioSesion;
import TiendaController.ProductosController;


/**
 *
 * @author Anderson Diaz
 */
public class CatalogoProducto extends javax.swing.JFrame {

    private static CatalogoProducto catalogoProducto;
    public int cantidProd;
    /**
     * Creates new form catalogoCocina
     */
    public CatalogoProducto() {
        initComponents();
    }
    
    public static CatalogoProducto getInstance(){
        if(catalogoProducto==null)
            catalogoProducto=new CatalogoProducto();
        return catalogoProducto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_3_Boton_Opciones = new javax.swing.JPanel();
        btnProdAnterior = new javax.swing.JButton();
        btnProdSiguiente = new javax.swing.JButton();
        Panel_1_Logo_Tienda = new javax.swing.JPanel();
        Logo_Tienda = new javax.swing.JLabel();
        jlbTitCat = new javax.swing.JLabel();
        Panel_2_Boton_Seleccion = new javax.swing.JPanel();
        btnProd1 = new javax.swing.JButton();
        btnProd2 = new javax.swing.JButton();
        btnProd3 = new javax.swing.JButton();
        btnProd4 = new javax.swing.JButton();
        Menu_Principal = new javax.swing.JMenuBar();
        Panel_Menu_Configuracion = new javax.swing.JMenu();
        Menu_Usuario = new javax.swing.JMenu();
        Nombre = new javax.swing.JMenuItem();
        Apodo = new javax.swing.JMenuItem();
        Genero = new javax.swing.JMenuItem();
        Cumpleaños = new javax.swing.JMenuItem();
        Telefono = new javax.swing.JMenuItem();
        Correo = new javax.swing.JMenuItem();
        Redes = new javax.swing.JMenuItem();
        Contraseña = new javax.swing.JMenuItem();
        Menu_Soporte = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        Panel_Menu_General = new javax.swing.JMenu();
        Menu_Compras = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        Menu_Cargos = new javax.swing.JMenu();
        Efectivo_Agregado = new javax.swing.JMenuItem();
        Puntos_Agregados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_3_Boton_Opciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones."));
        Panel_3_Boton_Opciones.setLayout(new java.awt.GridLayout(1, 0));

        btnProdAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Retroceder.png"))); // NOI18N
        btnProdAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdAnteriorActionPerformed(evt);
            }
        });
        Panel_3_Boton_Opciones.add(btnProdAnterior);

        btnProdSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Avanzar.png"))); // NOI18N
        btnProdSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdSiguienteActionPerformed(evt);
            }
        });
        Panel_3_Boton_Opciones.add(btnProdSiguiente);

        getContentPane().add(Panel_3_Boton_Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 410, 80));

        Panel_1_Logo_Tienda.setLayout(new java.awt.GridLayout(2, 1));

        Logo_Tienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Diseño sin título (1) (1) (1).png"))); // NOI18N
        Panel_1_Logo_Tienda.add(Logo_Tienda);

        jlbTitCat.setFont(new java.awt.Font("Viner Hand ITC", 1, 36)); // NOI18N
        jlbTitCat.setForeground(new java.awt.Color(255, 0, 255));
        jlbTitCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTitCat.setText("CATALOGO COCINA");
        Panel_1_Logo_Tienda.add(jlbTitCat);

        getContentPane().add(Panel_1_Logo_Tienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 412, 240));

        Panel_2_Boton_Seleccion.setLayout(new java.awt.GridLayout(0, 2, 5, 5));

        btnProd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/venta-online (1).png"))); // NOI18N
        Panel_2_Boton_Seleccion.add(btnProd1);

        btnProd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/carton-de-huevos (1).png"))); // NOI18N
        Panel_2_Boton_Seleccion.add(btnProd2);

        btnProd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/control-de-juego (1).png"))); // NOI18N
        Panel_2_Boton_Seleccion.add(btnProd3);

        btnProd4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tienda-online (1).png"))); // NOI18N
        btnProd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProd4ActionPerformed(evt);
            }
        });
        Panel_2_Boton_Seleccion.add(btnProd4);

        getContentPane().add(Panel_2_Boton_Seleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 242, 412, 270));

        Panel_Menu_Configuracion.setText("Configuración.");

        Menu_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/perfil (1).png"))); // NOI18N
        Menu_Usuario.setText("Usuario.");

        Nombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Apellido - Nombre.png"))); // NOI18N
        Nombre.setText("Nombre.");
        Menu_Usuario.add(Nombre);

        Apodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Apellido - Nombre.png"))); // NOI18N
        Apodo.setText("Apodo.");
        Menu_Usuario.add(Apodo);

        Genero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Genero.png"))); // NOI18N
        Genero.setText("Genero.");
        Genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroActionPerformed(evt);
            }
        });
        Menu_Usuario.add(Genero);

        Cumpleaños.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cumpleaños.png"))); // NOI18N
        Cumpleaños.setText("Cumpleaños.");
        Menu_Usuario.add(Cumpleaños);

        Telefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Telefono.png"))); // NOI18N
        Telefono.setText("Telefono.");
        Menu_Usuario.add(Telefono);

        Correo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Correo.png"))); // NOI18N
        Correo.setText("Correo.");
        Menu_Usuario.add(Correo);

        Redes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Redes.png"))); // NOI18N
        Redes.setText("Redes.");
        Menu_Usuario.add(Redes);

        Contraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Contraseñas.png"))); // NOI18N
        Contraseña.setText("Contraseña.");
        Menu_Usuario.add(Contraseña);

        Panel_Menu_Configuracion.add(Menu_Usuario);

        Menu_Soporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Tecnico.png"))); // NOI18N
        Menu_Soporte.setText("Soporte.");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Asistencia.png"))); // NOI18N
        jMenuItem2.setText("Asistencia.");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Menu_Soporte.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Politica.png"))); // NOI18N
        jMenuItem3.setText("Politica.");
        Menu_Soporte.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Calificanos.png"))); // NOI18N
        jMenuItem4.setText("Calificanos.");
        Menu_Soporte.add(jMenuItem4);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Acerca de.png"))); // NOI18N
        jMenuItem8.setText("Acerca de.");
        Menu_Soporte.add(jMenuItem8);

        Panel_Menu_Configuracion.add(Menu_Soporte);

        Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, 0));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Salir.jpg"))); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Panel_Menu_Configuracion.add(Salir);

        Menu_Principal.add(Panel_Menu_Configuracion);

        Panel_Menu_General.setText("General.");

        Menu_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Compras.png"))); // NOI18N
        Menu_Compras.setText("Compras.");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Producto.png"))); // NOI18N
        jMenuItem9.setText("Producto 1.");
        Menu_Compras.add(jMenuItem9);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Producto.png"))); // NOI18N
        jMenuItem15.setText("Producto 2.");
        Menu_Compras.add(jMenuItem15);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Producto.png"))); // NOI18N
        jMenuItem16.setText("Producto 3.");
        Menu_Compras.add(jMenuItem16);

        Panel_Menu_General.add(Menu_Compras);

        Menu_Cargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cargo de pago.png"))); // NOI18N
        Menu_Cargos.setText("Cargo total.");

        Efectivo_Agregado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Efectivo.png"))); // NOI18N
        Efectivo_Agregado.setText("Efectivo agregado.");
        Menu_Cargos.add(Efectivo_Agregado);

        Puntos_Agregados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Puntos.png"))); // NOI18N
        Puntos_Agregados.setText("Puntos agregados.");
        Menu_Cargos.add(Puntos_Agregados);

        Panel_Menu_General.add(Menu_Cargos);

        Menu_Principal.add(Panel_Menu_General);

        setJMenuBar(Menu_Principal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_SalirActionPerformed

    private void btnProd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProd4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProd4ActionPerformed

    private void btnProdAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdAnteriorActionPerformed
        // TODO add your handling code here:
        cantidProd = cantidProd - 4;
    }//GEN-LAST:event_btnProdAnteriorActionPerformed

    private void btnProdSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdSiguienteActionPerformed
        // TODO add your handling code here:
        cantidProd = cantidProd + 4;
        
    }//GEN-LAST:event_btnProdSiguienteActionPerformed

    public void SeleccionTituloCatalogo (int selecTipo){
        String titCatalogo = "";
        if (selecTipo == 0){
            titCatalogo = "Catalogo Ropa";
        }else if (selecTipo == 1){
            titCatalogo = "Catalogo Cocina";
        }else if (selecTipo == 2){
            titCatalogo = "Catalogo Juguetes";
        }else if (selecTipo == 1){
            titCatalogo = "Catalogo Tecnología";
        }
        jlbTitCat.setText(titCatalogo);
        ProductosController catalogo = ProductosController.getInstance();
        String [][] productos = catalogo.MostrarCatalogo(selecTipo, cantidProd);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Apodo;
    private javax.swing.JMenuItem Contraseña;
    private javax.swing.JMenuItem Correo;
    private javax.swing.JMenuItem Cumpleaños;
    private javax.swing.JMenuItem Efectivo_Agregado;
    private javax.swing.JMenuItem Genero;
    private javax.swing.JLabel Logo_Tienda;
    private javax.swing.JMenu Menu_Cargos;
    private javax.swing.JMenu Menu_Compras;
    private javax.swing.JMenuBar Menu_Principal;
    private javax.swing.JMenu Menu_Soporte;
    private javax.swing.JMenu Menu_Usuario;
    private javax.swing.JMenuItem Nombre;
    private javax.swing.JPanel Panel_1_Logo_Tienda;
    private javax.swing.JPanel Panel_2_Boton_Seleccion;
    private javax.swing.JPanel Panel_3_Boton_Opciones;
    private javax.swing.JMenu Panel_Menu_Configuracion;
    private javax.swing.JMenu Panel_Menu_General;
    private javax.swing.JMenuItem Puntos_Agregados;
    private javax.swing.JMenuItem Redes;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem Telefono;
    private javax.swing.JButton btnProd1;
    private javax.swing.JButton btnProd2;
    private javax.swing.JButton btnProd3;
    private javax.swing.JButton btnProd4;
    private javax.swing.JButton btnProdAnterior;
    private javax.swing.JButton btnProdSiguiente;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JLabel jlbTitCat;
    // End of variables declaration//GEN-END:variables
}
