/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProductosTienda;

import DAOtienda.DAOproductos;
import MenuPrincipal.MenuTienda;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import TiendaController.ProductosController;

/**
 *
 * @author dafer
 */
public class MostrarProductos extends javax.swing.JFrame {

    private static MostrarProductos instancia=null;
    private DefaultTableModel modeloProducto;
    /**
     * Creates new form MostrarPokemon 
     */
    private MostrarProductos() {
        initComponents();
    }
    
    private void ActuListaProducto(){
        DAOproductos prodCont = ProductosController.getInstance();
        modeloProducto = prodCont.MostrarProductos();
        jTProducto.setModel(modeloProducto);
    }
    
    public static MostrarProductos getInstance(){
        if(instancia==null)
            instancia=new MostrarProductos();
        instancia.ActuListaProducto();
        return instancia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProducto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pokemones capturados");
        getContentPane().add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton3.setText("Agregar pokemon");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setText("Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton2.setText("MostrarDatos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jTProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTProducto);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.ActuListaProducto();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ProveedorProducto interfaz = ProveedorProducto.getInstance();
        interfaz.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuTienda menuprincipal = MenuTienda.getInstance();
        menuprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null,"["+jTable2.getSelectedRow()+","+jTable2.getSelectedColumn()+"]");
        try{
            if(jTProducto.getSelectedRow()>=0){
                String seleccionTxt=""+modeloProducto.getValueAt(jTProducto.getSelectedRow(),jTProducto.getSelectedColumn());
                if(!seleccionTxt.equals("null")){
                    //Arreglo de producto
                    String[] pokemon=new String[6];
                    for(int i=0;i<6;i++){
                        pokemon[i]=modeloProducto.getValueAt(jTProducto.getSelectedRow(),i).toString();
                    }
                    EditarPokemon editar = EditarPokemon.getInstance();
                    editar.setVisible(true);
                    editar.porDefecto();
                    editar.datosPorActualizar(pokemon);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null,"Debe seleccionar un campo no vacio", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Debe seleccionar un elemento", "Advertencia", JOptionPane.ERROR_MESSAGE);
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
            if(jTProducto.getSelectedRow()>=0){
                String seleccionTxt=""+modeloProducto.getValueAt(jTProducto.getSelectedRow(),jTProducto.getSelectedColumn());
                if(!seleccionTxt.equals("null")){
                    //Arreglo de producto
                    String[] producto = new String[6];
                    for(int i = 0;i < 6;i++){
                        producto[i]=modeloProducto.getValueAt(jTProducto.getSelectedRow(),i).toString();
                    }
                    
                    ProductosController eliminar = ProductosController.getInstance();
                    //eliminar.EliminarPokemon(producto);
                    int seleccion = JOptionPane.showConfirmDialog(this, "¿Deseas eliminar este pokemon?");
                    if(seleccion == 0){
                      if (eliminar.EliminarProducto(producto))
                          JOptionPane.showMessageDialog(this, "Eliminado Existoso");
                    }
                    ActuListaProducto();
                    //ActuListaPokemon();
                }else{
                    JOptionPane.showMessageDialog(null,"Debe seleccionar un campo no vacio", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null,"Debe seleccionar un elemento", "Advertencia", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTProducto;
    // End of variables declaration//GEN-END:variables
}
