/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu_Principal;

/**
 *
 * @author Antony Salcedo
 */
public class Menu_1 extends javax.swing.JFrame {

    /**
     * Creates new form Menu_1
     */
    public Menu_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_1_Logo_Tienda = new javax.swing.JPanel();
        Logo_Tienda = new javax.swing.JLabel();
        Panel_2_Boton_Seleccion = new javax.swing.JPanel();
        Boton_Venta_Ropa = new javax.swing.JButton();
        Boton_Venta_Alimentos = new javax.swing.JButton();
        Boton_Venta_Videojuegos = new javax.swing.JButton();
        Boton_Venta_Tecnologia = new javax.swing.JButton();
        Panel_3_Boton_Opciones = new javax.swing.JPanel();
        Boton_Retroceder = new javax.swing.JButton();
        Boton_Avanzar = new javax.swing.JButton();
        Menu_Principal = new javax.swing.JMenuBar();
        Panel_Menu_Configuracion = new javax.swing.JMenu();
        Menu_Usuario = new javax.swing.JMenu();
        Nombre = new javax.swing.JMenuItem();
        Apodo = new javax.swing.JMenuItem();
        Genero = new javax.swing.JMenuItem();
        Cumpleaños = new javax.swing.JMenuItem();
        Telefono = new javax.swing.JMenuItem();
        Correo = new javax.swing.JMenuItem();
        Redes = new javax.swing.JMenuItem();
        Contraseña = new javax.swing.JMenuItem();
        Menu_Soporte = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        Panel_Menu_General = new javax.swing.JMenu();
        Menu_Compras = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        Menu_Cargos = new javax.swing.JMenu();
        Efectivo_Agregado = new javax.swing.JMenuItem();
        Puntos_Agregados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_1_Logo_Tienda.setLayout(new java.awt.GridLayout(1, 0));

        Logo_Tienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Diseño sin título (1) (1).png"))); // NOI18N
        Panel_1_Logo_Tienda.add(Logo_Tienda);

        getContentPane().add(Panel_1_Logo_Tienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 412, 240));

        Panel_2_Boton_Seleccion.setLayout(new java.awt.GridLayout(0, 2, 5, 5));

        Boton_Venta_Ropa.setBackground(new java.awt.Color(255, 255, 255));
        Boton_Venta_Ropa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/venta-online (1).png"))); // NOI18N
        Panel_2_Boton_Seleccion.add(Boton_Venta_Ropa);

        Boton_Venta_Alimentos.setBackground(new java.awt.Color(255, 255, 255));
        Boton_Venta_Alimentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/carton-de-huevos (1).png"))); // NOI18N
        Panel_2_Boton_Seleccion.add(Boton_Venta_Alimentos);

        Boton_Venta_Videojuegos.setBackground(new java.awt.Color(255, 255, 255));
        Boton_Venta_Videojuegos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/control-de-juego (1).png"))); // NOI18N
        Panel_2_Boton_Seleccion.add(Boton_Venta_Videojuegos);

        Boton_Venta_Tecnologia.setBackground(new java.awt.Color(255, 255, 255));
        Boton_Venta_Tecnologia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tienda-online (1).png"))); // NOI18N
        Boton_Venta_Tecnologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Venta_TecnologiaActionPerformed(evt);
            }
        });
        Panel_2_Boton_Seleccion.add(Boton_Venta_Tecnologia);

        getContentPane().add(Panel_2_Boton_Seleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 242, 412, 270));

        Panel_3_Boton_Opciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones."));
        Panel_3_Boton_Opciones.setLayout(new java.awt.GridLayout());

        Boton_Retroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Retroceder.png"))); // NOI18N
        Panel_3_Boton_Opciones.add(Boton_Retroceder);

        Boton_Avanzar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Avanzar.png"))); // NOI18N
        Panel_3_Boton_Opciones.add(Boton_Avanzar);

        getContentPane().add(Panel_3_Boton_Opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 410, 80));

        Panel_Menu_Configuracion.setText("Configuración.");

        Menu_Usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/perfil (1).png"))); // NOI18N
        Menu_Usuario.setText("Usuario.");

        Nombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Apellido - Nombre.png"))); // NOI18N
        Nombre.setText("Nombre.");
        Menu_Usuario.add(Nombre);

        Apodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Apellido - Nombre.png"))); // NOI18N
        Apodo.setText("Apodo.");
        Menu_Usuario.add(Apodo);

        Genero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Genero.png"))); // NOI18N
        Genero.setText("Genero.");
        Genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeneroActionPerformed(evt);
            }
        });
        Menu_Usuario.add(Genero);

        Cumpleaños.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cumpleaños.png"))); // NOI18N
        Cumpleaños.setText("Cumpleaños.");
        Menu_Usuario.add(Cumpleaños);

        Telefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Telefono.png"))); // NOI18N
        Telefono.setText("Telefono.");
        Menu_Usuario.add(Telefono);

        Correo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Correo.png"))); // NOI18N
        Correo.setText("Correo.");
        Menu_Usuario.add(Correo);

        Redes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Redes.png"))); // NOI18N
        Redes.setText("Redes.");
        Menu_Usuario.add(Redes);

        Contraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Contraseñas.png"))); // NOI18N
        Contraseña.setText("Contraseña.");
        Menu_Usuario.add(Contraseña);

        Panel_Menu_Configuracion.add(Menu_Usuario);

        Menu_Soporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Tecnico.png"))); // NOI18N
        Menu_Soporte.setText("Soporte.");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Asistencia.png"))); // NOI18N
        jMenuItem2.setText("Asistencia.");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Menu_Soporte.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Politica.png"))); // NOI18N
        jMenuItem3.setText("Politica.");
        Menu_Soporte.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Calificanos.png"))); // NOI18N
        jMenuItem4.setText("Calificanos.");
        Menu_Soporte.add(jMenuItem4);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Acerca de.png"))); // NOI18N
        jMenuItem8.setText("Acerca de.");
        Menu_Soporte.add(jMenuItem8);

        Panel_Menu_Configuracion.add(Menu_Soporte);

        Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, 0));
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Salir.jpg"))); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        Panel_Menu_Configuracion.add(Salir);

        Menu_Principal.add(Panel_Menu_Configuracion);

        Panel_Menu_General.setText("General.");

        Menu_Compras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Compras.png"))); // NOI18N
        Menu_Compras.setText("Compras.");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Producto.png"))); // NOI18N
        jMenuItem9.setText("Producto 1.");
        Menu_Compras.add(jMenuItem9);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Producto.png"))); // NOI18N
        jMenuItem15.setText("Producto 2.");
        Menu_Compras.add(jMenuItem15);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Producto.png"))); // NOI18N
        jMenuItem16.setText("Producto 3.");
        Menu_Compras.add(jMenuItem16);

        Panel_Menu_General.add(Menu_Compras);

        Menu_Cargos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Cargo de pago.png"))); // NOI18N
        Menu_Cargos.setText("Cargo total.");

        Efectivo_Agregado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Efectivo.png"))); // NOI18N
        Efectivo_Agregado.setText("Efectivo agregado.");
        Menu_Cargos.add(Efectivo_Agregado);

        Puntos_Agregados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Puntos.png"))); // NOI18N
        Puntos_Agregados.setText("Puntos agregados.");
        Menu_Cargos.add(Puntos_Agregados);

        Panel_Menu_General.add(Menu_Cargos);

        Menu_Principal.add(Panel_Menu_General);

        setJMenuBar(Menu_Principal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_Venta_TecnologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Venta_TecnologiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_Venta_TecnologiaActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SalirActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void GeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Apodo;
    private javax.swing.JButton Boton_Avanzar;
    private javax.swing.JButton Boton_Retroceder;
    private javax.swing.JButton Boton_Venta_Alimentos;
    private javax.swing.JButton Boton_Venta_Ropa;
    private javax.swing.JButton Boton_Venta_Tecnologia;
    private javax.swing.JButton Boton_Venta_Videojuegos;
    private javax.swing.JMenuItem Contraseña;
    private javax.swing.JMenuItem Correo;
    private javax.swing.JMenuItem Cumpleaños;
    private javax.swing.JMenuItem Efectivo_Agregado;
    private javax.swing.JMenuItem Genero;
    private javax.swing.JLabel Logo_Tienda;
    private javax.swing.JMenu Menu_Cargos;
    private javax.swing.JMenu Menu_Compras;
    private javax.swing.JMenuBar Menu_Principal;
    private javax.swing.JMenu Menu_Soporte;
    private javax.swing.JMenu Menu_Usuario;
    private javax.swing.JMenuItem Nombre;
    private javax.swing.JPanel Panel_1_Logo_Tienda;
    private javax.swing.JPanel Panel_2_Boton_Seleccion;
    private javax.swing.JPanel Panel_3_Boton_Opciones;
    private javax.swing.JMenu Panel_Menu_Configuracion;
    private javax.swing.JMenu Panel_Menu_General;
    private javax.swing.JMenuItem Puntos_Agregados;
    private javax.swing.JMenuItem Redes;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenuItem Telefono;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
