/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UsuariosTienda;

import DAOtienda.DAOusuarios;
import MenuPrincipal.MenuTienda;
import TiendaController.UsuariosController;
import javax.swing.JOptionPane;

/**
 *
 * @author Anderson Diaz
 */
public class AgregarUsuario extends javax.swing.JFrame {

    private static AgregarUsuario agregarUsuario;
    
    /**
     * Creates new form agregarUsuario
     */
    private AgregarUsuario() {
        initComponents();
    }
    
    public static AgregarUsuario getInstance(){
        if(agregarUsuario == null)
            agregarUsuario = new AgregarUsuario();
        agregarUsuario.porDefecto();
        return agregarUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void porDefecto(){
        txtUsuNomb.setText("Nombre");
        txtUsuApe.setText("Apellido");
        rD_Ma.setSelected(false);
        rD_Fe.setSelected(false);
        rD_He.setSelected(false);
        sexo.clearSelection();
        txtNumIden.setText("Número de identificación");
        txtUsuNum.setText("Número de teléfono");
        txtUsusCorr.setText("Correo Electróncio");
        jPasswordField1.setText("*Contraseña*");
        jPasswordField2.setText("*Confirmar Contraseña*");
   }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        txtUsuNomb = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        txtUsuApe = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        txtNumIden = new javax.swing.JTextField();
        cboIdent = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        rD_Ma = new javax.swing.JRadioButton();
        rD_Fe = new javax.swing.JRadioButton();
        rD_He = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        txtUsuNum = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        txtUsusCorr = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Registro Usuario");
        getContentPane().add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres (MAYUSCULA)"));
        jPanel9.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        txtUsuNomb.setText("Nombres");
        txtUsuNomb.setToolTipText("");
        txtUsuNomb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuNombMouseClicked(evt);
            }
        });
        txtUsuNomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuNombActionPerformed(evt);
            }
        });
        txtUsuNomb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuNombKeyTyped(evt);
            }
        });
        jPanel9.add(txtUsuNomb);

        jPanel1.add(jPanel9);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellidos (MAYUSCULA)"));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        txtUsuApe.setText("Apellidos");
        txtUsuApe.setToolTipText("");
        txtUsuApe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuApeMouseClicked(evt);
            }
        });
        jPanel5.add(txtUsuApe);

        jPanel1.add(jPanel5);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Identificación"));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumIden.setText("N° Identificacion");
        txtNumIden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNumIdenMouseClicked(evt);
            }
        });
        txtNumIden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumIdenActionPerformed(evt);
            }
        });
        jPanel8.add(txtNumIden, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 18, 310, 40));

        cboIdent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C.C", "T.I", "P.A" }));
        jPanel8.add(cboIdent, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 22, -1, 30));

        jPanel1.add(jPanel8);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Sexo"));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        sexo.add(rD_Ma);
        rD_Ma.setText("Masculino");
        jPanel3.add(rD_Ma);

        sexo.add(rD_Fe);
        rD_Fe.setText("Femenino");
        jPanel3.add(rD_Fe);

        sexo.add(rD_He);
        rD_He.setText("Hermafrodita");
        jPanel3.add(rD_He);

        jPanel1.add(jPanel3);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Número de Contacto"));
        jPanel6.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        txtUsuNum.setText("Número");
        txtUsuNum.setToolTipText("");
        txtUsuNum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuNumMouseClicked(evt);
            }
        });
        txtUsuNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuNumActionPerformed(evt);
            }
        });
        txtUsuNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuNumKeyTyped(evt);
            }
        });
        jPanel6.add(txtUsuNum);

        jPanel1.add(jPanel6);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Correo Electrónico"));
        jPanel10.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        txtUsusCorr.setText("Correo");
        txtUsusCorr.setToolTipText("");
        txtUsusCorr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsusCorrMouseClicked(evt);
            }
        });
        txtUsusCorr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsusCorrActionPerformed(evt);
            }
        });
        txtUsusCorr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsusCorrKeyTyped(evt);
            }
        });
        jPanel10.add(txtUsusCorr);

        jPanel1.add(jPanel10);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));
        jPanel11.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jPanel11.setLayout(new java.awt.GridLayout(2, 2));

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPanel11.add(jPasswordField1);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contraseña");
        jPanel11.add(jLabel1);

        jPasswordField2.setText("jPasswordField2");
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
        });
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPanel11.add(jPasswordField2);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("*Confirmar contraseña*");
        jPanel11.add(jLabel2);

        jPanel1.add(jPanel11);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Guardar Ususario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1);

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2);

        getContentPane().add(jPanel7, java.awt.BorderLayout.PAGE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuNumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuNumMouseClicked
        // TODO add your handling code here:
        txtUsuNum.setText("");
    }//GEN-LAST:event_txtUsuNumMouseClicked

    private void txtUsuNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuNumKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())) evt.consume();
    }//GEN-LAST:event_txtUsuNumKeyTyped

    private void txtUsuApeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuApeMouseClicked
        // TODO add your handling code here:
        txtUsuApe.setText("");
    }//GEN-LAST:event_txtUsuApeMouseClicked

    private void txtUsuNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuNumActionPerformed

    private void txtNumIdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumIdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumIdenActionPerformed

    private void txtUsuNombMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuNombMouseClicked
        // TODO add your handling code here:
        txtUsuNomb.setText("");
    }//GEN-LAST:event_txtUsuNombMouseClicked

    private void txtUsuNombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuNombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuNombActionPerformed

    private void txtUsuNombKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuNombKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuNombKeyTyped

    private void txtUsusCorrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsusCorrMouseClicked
        // TODO add your handling code here:
        txtUsusCorr.setText("");
    }//GEN-LAST:event_txtUsusCorrMouseClicked

    private void txtUsusCorrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsusCorrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsusCorrActionPerformed

    private void txtUsusCorrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsusCorrKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsusCorrKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MenuTienda menuprincipal = MenuTienda.getInstance();
        menuprincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DAOusuarios usuCont = UsuariosController.getInstance();
        String nomUsu = txtUsuNomb.getText();
        String apeUsu = txtUsuApe.getText();
        String sexUsu = "";
        String idenUsu = cboIdent.getSelectedItem().toString() + txtNumIden.toString();
        String numUsu = txtUsuNum.getText();
        String corrUsu = txtUsusCorr.getText();
        String passUsu = "";
        if(rD_Ma.isSelected()){
            sexUsu = "Masculino";
        }else if (rD_Fe.isSelected()){
            sexUsu = "Femenino";
        }else{
            sexUsu = "Hermafrodita";
        }
        System.out.println(jPasswordField1.getText());
        System.out.println(jPasswordField2.getText());
        if (jPasswordField1.getText().equals(jPasswordField2.getText())){
            JOptionPane.showMessageDialog(this, "Las contraseñas coinciden");
            passUsu = jPasswordField2.getText();
            String[] usuario = {nomUsu, apeUsu, idenUsu, sexUsu, numUsu, corrUsu, passUsu};
            if(usuCont.GuardarUsuario(usuario))
            JOptionPane.showMessageDialog(this, "Guardado Exitoso");
        }
        else if (jPasswordField1.getText()!= jPasswordField2.getText()){
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden","Error!",JOptionPane.ERROR_MESSAGE);
            jPasswordField1.setText("");
            jPasswordField2.setText("");
        }else{
            JOptionPane.showMessageDialog(this, "Digite las contraseñas");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void txtNumIdenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNumIdenMouseClicked
        // TODO add your handling code here:
        txtNumIden.setText("");
    }//GEN-LAST:event_txtNumIdenMouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        // TODO add your handling code here:
        jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked
        // TODO add your handling code here:
        jPasswordField2.setText("");
    }//GEN-LAST:event_jPasswordField2MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboIdent;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JRadioButton rD_Fe;
    private javax.swing.JRadioButton rD_He;
    private javax.swing.JRadioButton rD_Ma;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.JTextField txtNumIden;
    private javax.swing.JTextField txtUsuApe;
    private javax.swing.JTextField txtUsuNomb;
    private javax.swing.JTextField txtUsuNum;
    private javax.swing.JTextField txtUsusCorr;
    // End of variables declaration//GEN-END:variables
}
